cd ""

clear
set more off
use "Merge_201407_N.dta"

tab exam_motive if dataset =="CCE", matcell(freq)
mat A1 = freq
mat list A1

tab exam_motive if dataset =="DB", matcell(freq)
mat B1 = freq
mat list B1

mat total_col = regexr(A1-B1,)
mat list total_col

tab exam_motive dataset, matcell(freq)
mat R = J(1,rowsof(freq),1)
mat list R
mat total_row = R*freq
mat list total_row
mat T = J(2,1,1)
mat total = total_row*T
mat list total

levelsof exam_motive, local(code)

/* 값을 더하거나 곱할 때에는 행렬수학의 법칙을 바로 적용할 수 있다.

예를 들어
(3 2
 2 4    X (2  을 구할 때에는 tab을 한 후에 바로 적용할 수 있다.
 1 5)      1)

더할 때에는 다음과 같은 법칙을 적용할 수 있다.
(3 2
 2 4    X (1  을 구할 때에는 tab을 한 후에 바로 적용할 수 있다.
 1 5)      1)
 그래서 J(x,y,z)라는 법칙을 적용할 수 있는 것.
 여기서 x는 행, y는 열의 갯수를 의미하고 z는 상수 값을 의미함.

*/

// 작업 샘플
clear
set more off
use "Merge_201407_N.dta"
foreach var of varlist * {
	replace `var' = "." if `var' == ""
}

putexcel set ".\TT.xlsx", sheet("TT") modify

***** 귀찮으니까 그냥 781개 다 돌리고 쉽시다 ^^! 오래걸려요
local vars "exam_motive exam exam_first_age exam_most_recent_yy exam_most_recent_mm exam_freq_yr exam_place marital_status education income smk_ys smk smk_duration smk_current_amount smk_start_age smk_endyr smk_packyrs alc_ys alc alc_freq alc_amount_drinks alc_start_age alc_duration alc_endyr alc_amount_grams phy overall_physical_activity phy_freq_2009 phy_duration_2009 phy_freq phy_duration phy_startyr phy_walking phy_jogging phy_tennis phy_golf phy_swimming phy_climbing phy_aerobic phy_fitness phy_other allergy allergy_penicillin allergy_sulfa allergy_contrast_agent allergy_local_anesthetic allergy_aspirin allergy_other allergy_unknown adverse_med adverse_med_antibiotics adverse_med_contrast_agent adverse_med_local_anesthetic adverse_med_aspirin_painkiller adverse_med_other surgery_stomach surgery_gallbladder surgery_colon surgery_appendix surgery_thyroid surgery_uterus surgery_ovary surgery_breast surgery_kidney surgery_other history_comorbidity history_tuberculosis trt_tuberculosis status_tuberculosis trt_tuberculosis_op tuberculosis_age_diag history_hypertension trt_hypertension status_hypertension hypertension_age_diag history_hyperlipidemia trt_hyperlipidemia status_hyperlipidemia hyperlipidemia_age_diag history_stroke trt_stroke status_stroke trt_stroke_op stroke_age_diag history_diabetes trt_diabetes status_diabetes diabetes_age_diag history_ga_duodenal_ulcer trt_ga_duodenal_ulcer status_ga_duodenal_ulcer trt_ga_duodenal_ulcer_op ga_duodenal_ulcer_age_diag history_colon_polyp trt_colon_polyp status_colon_polyp trt_colon_polyp_op colon_polyp_age_diag history_fatty_liver trt_fatty_liver status_fatty_liver fatty_liver_age_diag history_thyroid_nodules trt_thyroid_nodules status_thyroid_nodules trt_thyroid_nodules_op thyroid_nodules_age_diag history_bbt trt_bbt status_bbt trt_bbt_op bbt_age_diag trt_bbt_biopsy history_disc trt_disc status_disc trt_disc_op disc_age_diag history_gastritis trt_gastritis gastritis_age_diag history_enteritis trt_enteritis enteritis_age_diag history_hemorrhoid trt_hemorrhoid hemorrhoid_age_diag history_acute_hep trt_acute_hep acute_hep_age_diag history_hep_cirrhosis trt_hep_cirrhosis hep_cirrhosis_age_diag history_gallbladder_dis trt_gallbladder_dis gallbladder_dis_age_diag history_myoma_uteri trt_myoma_uteri_op myoma_uteri_age_diag history_cervicitis trt_cervicitis_op cervicitis_age_diag history_trauma trt_trauma trauma_age_diag history_hbv trt_hbv status_hbv hbv_age_diag history_hcv trt_hcv status_hcv hcv_age_diag history_cirrhosis trt_cirrhosis status_cirrhosis cirrhosis_age_diag history_helico_pylori trt_helico_pylori status_helico_pylori helico_pylori_age_diag history_copd trt_history_copd status_history_copd copd_age_diag history_arthritis trt_arthritis status_arthritis trt_arthritis_op arthritis_age_diag history_cataract trt_cataract status_cataract trt_cataract_op cataract_age_diag history_glaucoma trt_glaucoma status_glaucoma trt_glaucoma_op glaucoma_age_diag history_asthma_allergy trt_asthma_allergy asthma_allergy_age_diag history_asthma trt_asthma status_asthma asthma_age_diag history_coronary_dis trt_coronary_dis coronary_dis_age_diag history_angina trt_angina status_angina trt_angina_op angina_age_diag history_mi trt_mi status_mi trt_mi_op mi_age_diag history_kidney_urinary_dis trt_kidney_urinary_dis status_kidney_urinary_dis trt_kidney_urinary_dis_op kidney_urinary_dis_age_diag history_kidney_dis trt_kidney_dis kidney_dis_age_diag history_urinary_tract_dis trt_urinary_tract_dis urinary_tract_dis_age_diag history_thyroid_dis1 trt_thyroid_dis1 thyroid_dis1_age_diag history_bph trt_bph status_bph trt_bph_op bph_age_diag history_thyroid_dis2 trt_thyroid_dis2 status_thyroid_dis2 trt_thyroid_dis2_op thyroid_dis2_age_diag history_other trt_other status_other trt_other_op other_age_diag history_cancer history_cancer_stomach cancer_stomach_age_diag trt_cancer_stomach trt_cancer_stomach_op trt_cancer_stomach_ch trt_cancer_stomach_ra trt_cancer_stomach_ot history_cancer_lung cancer_lung_age_diag trt_cancer_lung trt_cancer_lung_op trt_cancer_lung_ch trt_cancer_lung_ra trt_cancer_lung_ot history_cancer_liver cancer_liver_age_diag trt_cancer_liver trt_cancer_liver_op trt_cancer_liver_ch trt_cancer_liver_ra trt_cancer_liver_ot history_cancer_colorectal cancer_colorectal_age_diag trt_cancer_colorectal trt_cancer_colorectal_op trt_cancer_colorectal_ch trt_cancer_colorectal_ra trt_cancer_colorectal_ot history_cancer_breast cancer_breast_age_diag trt_cancer_breast trt_cancer_breast_op trt_cancer_breast_ch trt_cancer_breast_ra trt_cancer_breast_ot history_cancer_cervix cancer_cervix_age_diag trt_cancer_cervix trt_cancer_cervix_op trt_cancer_cervix_ch trt_cancer_cervix_ra trt_cancer_cervix_ot history_cancer_thyroid cancer_thyroid_age_diag trt_cancer_thyroid trt_cancer_thyroid_op trt_cancer_thyroid_ch trt_cancer_thyroid_ra trt_cancer_thyroid_ot history_cancer_bladder cancer_bladder_age_diag trt_cancer_bladder trt_cancer_bladder_op trt_cancer_bladder_ch trt_cancer_bladder_ra trt_cancer_bladder_ot history_cancer_esophagus cancer_esophagus_age_diag trt_cancer_esophagus trt_cancer_esophagus_op trt_cancer_esophagus_ch trt_cancer_esophagus_ra trt_cancer_esophagus_ot history_cancer_gb_biliary cancer_gb_biliary_age_diag trt_cancer_gb_biliary trt_cancer_gb_biliary_op trt_cancer_gb_biliary_ch trt_cancer_gb_biliary_ra trt_cancer_gb_biliary_ot history_cancer_ovary cancer_ovary_age_diag trt_cancer_ovary trt_cancer_ovary_op trt_cancer_ovary_ch trt_cancer_ovary_ra trt_cancer_ovary_ot history_cancer_prostate cancer_prostate_age_diag trt_cancer_prostate trt_cancer_prostate_op trt_cancer_prostate_ch trt_cancer_prostate_ra trt_cancer_prostate_ot history_cancer_pancreas cancer_pancreas_age_diag trt_cancer_pancreas trt_cancer_pancreas_op trt_cancer_pancreas_ch trt_cancer_pancreas_ra trt_cancer_pancreas_ot history_cancer_other cancer_other_age_diag trt_cancer_other trt_cancer_other_op trt_cancer_other_ch trt_cancer_other_ra trt_cancer_other_ot med med_hypertension trt_med_hypertension med_hypertension_duration med_diabetes trt_med_diabetes med_diabetes_duration med_aspirin trt_med_aspirin med_aspirin_duration med_nsaids trt_med_nsaids med_nsaids_duration med_calcium trt_med_calcium med_calcium_duration med_iron trt_med_iron med_iron_duration med_cam trt_med_cam med_cam_duration med_beta_carotene med_beta_carotene_duration med_multi_vitamin med_multi_vitamin_duration med_vitamin_a med_vitamin_a_duration med_vitamin_b med_vitamin_b_duration med_vitamin_c med_vitamin_c_duration med_vitamin_e med_vitamin_e_duration med_other_supplements med_other_supplements_duration med_hyperlipidemia trt_med_hyperlipidemia med_warfarin trt_med_warfarin med_anticoagulant trt_med_anticoagulant med_arrhythmia trt_med_arrhythmia med_gi_digestives trt_med_gi_digestives med_liver trt_med_liver med_constipation trt_med_constipation med_thyroid_dis trt_med_thyroid_dis med_osteoporosis trt_med_osteoporosis med_female_hormones trt_med_female_hormones med_bph trt_med_bph med_respiratory_dis trt_med_respiratory_dis med_nutri_supplements trt_med_nutri_supplements med_sleeping_pills med_sleeping_pills_duration med_psychiatric trt_med_psychiatric med_other trt_med_other med_other_duration family family_hypertension_f family_hypertension_m family_hypertension_sib family_hypertension_ch family_hypertension_ff family_hypertension_fm family_hypertension_mf family_hypertension_mm family_stroke_f family_stroke_m family_stroke_sib family_stroke_ch family_stroke_ff family_stroke_fm family_stroke_mf family_stroke_mm family_diabetes_f family_diabetes_m family_diabetes_sib family_diabetes_ch family_diabetes_ff family_diabetes_fm family_diabetes_mf family_diabetes_mm family_hep_cirrhosis_f family_hep_cirrhosis_m family_hep_cirrhosis_sib family_hep_cirrhosis_ch family_hep_cirrhosis_ff family_hep_cirrhosis_fm family_hep_cirrhosis_mf family_hep_cirrhosis_mm family_dementia_f family_dementia_m family_dementia_sib family_dementia_ch family_dementia_ff family_dementia_fm family_dementia_mf family_dementia_mm family_tuberculosis_f family_tuberculosis_m family_tuberculosis_sib family_tuberculosis_ch family_tuberculosis_ff family_tuberculosis_fm family_tuberculosis_mf family_tuberculosis_mm family_mi_f family_mi_m family_mi_sib family_mi_ch family_mi_ff family_mi_fm family_mi_mf family_mi_mm family_angina_f family_angina_m family_angina_sib family_angina_ch family_angina_ff family_angina_fm family_angina_mf family_angina_mm family_other_congenital_mal_f family_other_congenital_mal_m family_other_congenital_mal_sib family_other_congenital_mal_ch family_other_congenital_mal_ff family_other_congenital_mal_fm family_other_congenital_mal_mf family_other_congenital_mal_mm family_congenital_heart_dis_f family_congenital_heart_dis_m family_congenital_heart_dis_sib family_congenital_heart_dis_ch family_congenital_heart_dis_ff family_congenital_heart_dis_fm family_congenital_heart_dis_mf family_congenital_heart_dis_mm family_cleft_lip_palate_f family_cleft_lip_palate_m family_cleft_lip_palate_sib family_cleft_lip_palate_ch family_cleft_lip_palate_ff family_cleft_lip_palate_fm family_cleft_lip_palate_mf family_cleft_lip_palate_mm family_coronary_dis_f family_coronary_dis_m family_coronary_dis_sib family_coronary_dis_ch family_coronary_dis_ff family_coronary_dis_fm family_coronary_dis_mf family_coronary_dis_mm family_asthma_copd_f family_asthma_copd_m family_asthma_copd_sib family_asthma_copd_ch family_asthma_copd_ff family_asthma_copd_fm family_asthma_copd_mf family_asthma_copd_mm family_cancer_stomach_f family_cancer_stomach_m family_cancer_stomach_sib family_cancer_stomach_ch family_cancer_stomach_ff family_cancer_stomach_fm family_cancer_stomach_mf family_cancer_stomach_mm family_cancer_breast_f family_cancer_breast_m family_cancer_breast_sib family_cancer_breast_ch family_cancer_breast_ff family_cancer_breast_fm family_cancer_breast_mf family_cancer_breast_mm family_cancer_colorectal_f family_cancer_colorectal_m family_cancer_colorectal_sib family_cancer_colorectal_ch family_cancer_colorectal_ff family_cancer_colorectal_fm family_cancer_colorectal_mf family_cancer_colorectal_mm family_cancer_lung_f family_cancer_lung_m family_cancer_lung_sib family_cancer_lung_ch family_cancer_lung_ff family_cancer_lung_fm family_cancer_lung_mf family_cancer_lung_mm family_cancer_uterine_f family_cancer_uterine_m family_cancer_uterine_sib family_cancer_uterine_ch family_cancer_uterine_ff family_cancer_uterine_fm family_cancer_uterine_mf family_cancer_uterine_mm family_cancer_liver_f family_cancer_liver_m family_cancer_liver_sib family_cancer_liver_ch family_cancer_liver_ff family_cancer_liver_fm family_cancer_liver_mf family_cancer_liver_mm family_cancer_thyroid_f family_cancer_thyroid_m family_cancer_thyroid_sib family_cancer_thyroid_ch family_cancer_thyroid_ff family_cancer_thyroid_fm family_cancer_thyroid_mf family_cancer_thyroid_mm family_cancer_ovary_f family_cancer_ovary_m family_cancer_ovary_sib family_cancer_ovary_ch family_cancer_ovary_ff family_cancer_ovary_fm family_cancer_ovary_mf family_cancer_ovary_mm family_cancer_cervix_f family_cancer_cervix_m family_cancer_cervix_sib family_cancer_cervix_ch family_cancer_cervix_ff family_cancer_cervix_fm family_cancer_cervix_mf family_cancer_cervix_mm family_cancer_gb_biliary_f family_cancer_gb_biliary_m family_cancer_gb_biliary_sib family_cancer_gb_biliary_ch family_cancer_gb_biliary_ff family_cancer_gb_biliary_fm family_cancer_gb_biliary_mf family_cancer_gb_biliary_mm family_cancer_bladder_f family_cancer_bladder_m family_cancer_bladder_sib family_cancer_bladder_ch family_cancer_bladder_ff family_cancer_bladder_fm family_cancer_bladder_mf family_cancer_bladder_mm family_cancer_esophagus_f family_cancer_esophagus_m family_cancer_esophagus_sib family_cancer_esophagus_ch family_cancer_esophagus_ff family_cancer_esophagus_fm family_cancer_esophagus_mf family_cancer_esophagus_mm family_cancer_prostate_f family_cancer_prostate_m family_cancer_prostate_sib family_cancer_prostate_ch family_cancer_prostate_ff family_cancer_prostate_fm family_cancer_prostate_mf family_cancer_prostate_mm family_cancer_pancreas_f family_cancer_pancreas_m family_cancer_pancreas_sib family_cancer_pancreas_ch family_cancer_pancreas_ff family_cancer_pancreas_fm family_cancer_pancreas_mf family_cancer_pancreas_mm family_cancer_other_f family_cancer_other_m family_cancer_other_sib family_cancer_other_ch family_cancer_other_ff family_cancer_other_fm family_cancer_other_mf family_cancer_other_mm ml1_1 ml2_1 ml3_1 ml4_1 ml5_1 ml6_1 ml7_1 ml8_1 ml_score menstruation_last_yy menstruation_last_mm menstruation_last_dd menarche_age no_menstruation menstruation_avg_duration abnormal_bleeding vaginal_discharge postmenopausal menopause_age_cat menopause_age menopause_cause female_hormones trt_female_hormones female_hormones_age female_hormones_amount female_hormones_duration pregnancy pregnancy_first_age delivery delivery_n delivery_boy delivery_girl natural_childbirth caesarean_section delivery_first_age delivery_last_age premature_birth premature_birth_n miscarriage miscarriage_natural_n miscarriage_artificial_n pap pap_first_age pap_last_age pap_freq stress_q1 stress_q2 stress_q3 stress_q4 stress_q5 stress_q6 stress_q7 stress_q8 stress_q9 stress_q10 stress_q11 stress_q12 stress_q13 stress_q14 stress_q15 stress_q16 stress_q17 stress_q18 stress_q19 stress_q20 stress_q21 stress_score sy1_1 sy1_2 sy1_3 sy1_4 sy1_5 sy1_6 sy1_7 sy1_8 sy1_9 sy1_10 sy1_11 sy1_12 sy1_13 sy1_14 sy1_15 sy1_16 sy1_17 sy1_18 sy1_19 sy1_20 sy1_21 sy2_1 sy2_2 sy2_3 sy2_4 sy2_5 sy2_6 sy2_7 sy3_1 sy3_2 sy3_3 sy3_4 sy3_5 sy3_6 sy3_7 sy3_8 sy3_9 sy3_10 sy4_1 sy4_2 sy4_3 sy4_4 sy4_5 sy4_6 sy5_1 sy5_2 sy5_3 sy5_4 sy5_5 sy5_6 sy5_7 sy6_1 sy6_2 sy6_3 sy6_4 sy6_5 sy6_6 sy6_7 sy6_8 sy6_9 sy7_1 sy7_2 sy7_3 sy7_4 sy7_5 sy7_6 sy7_7 sy8_1 sy8_2 sy8_3 sy8_4 sy8_5 sy8_6 sy8_7 sy8_8 sy8_9 sy8_10 sy9_1 sy9_2 sy9_3 sy9_4 sy9_5 sy9_6 sy9_7 sy9_8 sy9_9 sy9_10 sy9_11 sy9_12 sy9_13 sy9_14 sy9_15"

local i = 1
foreach var in `vars' {

	/***** 빈도수 저장
	tab `var' dataset, matcell(freq)*/

	***** total_column 저장
	tab `var' if dataset =="CCE", matcell(freq)
	mat A1 = freq

	tab `var' if dataset =="DB", matcell(freq)
	mat B1 = freq

	mat total_col = A1-B1
	
	/*
	
	차이를 구할 때에는 뺄쌤을 해야 하므로 각 dataset 별로
	matrix를 만들어서 행렬의 차이를 구해야 함.
	
	*/

	***** total_row 저장
	tab `var' dataset, matcell(freq)
	mat R = J(1,rowsof(freq),1)
	mat total_row = R*freq

	/*
	***** 전체 total 저장
	matrix temp = J(2,1,1)
	matrix total = total_row*temp
	*/

	***** 코드값 저장
	levelsof `var', local(code)

	***** 저장한 값들 put excel
	putexcel A`i' = ("`var'") B`i' = ("CCE") C`i' = ("DB") D`i' = ("difference"), hcenter border(bottom) fpattern(solid, "213 213 213") //맨 윗줄
	putexcel B`i' D`i', border(left) fpattern(solid, "213 213 213")
	local i = `i' +1

	putexcel B`i' = matrix(freq) D`i' = matrix(total_col) // 빈도수

	foreach c of local code {  //코드값
		putexcel A`i' = ("`c'") C`i', border(right)
		local i = `i' + 1
	}

	putexcel A`i' = ("Total") B`i' = matrix(total_row), border(top) //맨 아랫줄
	putexcel B`i' D`i', border(left)

	local i = `i' + 3  //두줄 띄우고 새로운 테이블 붙이기

}



clear
set more off
use "Merge_201407_N.dta"

tab exam dataset, matcell(freq)
mat A = (1\-1)
mat list A
mat total_col = freq*A
mat list total_col


// 작업 샘플 - 위에 형식으로 해 보니, 각각 dataset을 분류해서 작업하는 것은  변수의 row 변화를 카운트할 수가 없음.
clear
set more off
use "Merge_201407_N.dta"

putexcel set ".\TT.xlsx", sheet("TT") modify

***** 귀찮으니까 그냥 781개 다 돌리고 쉽시다 ^^! 오래걸려요
local vars "exam_motive exam exam_first_age exam_most_recent_yy exam_most_recent_mm exam_freq_yr exam_place marital_status education income smk_ys smk smk_duration smk_current_amount smk_start_age smk_endyr smk_packyrs alc_ys alc alc_freq alc_amount_drinks alc_start_age alc_duration alc_endyr alc_amount_grams phy overall_physical_activity phy_freq_2009 phy_duration_2009 phy_freq phy_duration phy_startyr phy_walking phy_jogging phy_tennis phy_golf phy_swimming phy_climbing phy_aerobic phy_fitness phy_other allergy allergy_penicillin allergy_sulfa allergy_contrast_agent allergy_local_anesthetic allergy_aspirin allergy_other allergy_unknown adverse_med adverse_med_antibiotics adverse_med_contrast_agent adverse_med_local_anesthetic adverse_med_aspirin_painkiller adverse_med_other surgery_stomach surgery_gallbladder surgery_colon surgery_appendix surgery_thyroid surgery_uterus surgery_ovary surgery_breast surgery_kidney surgery_other history_comorbidity history_tuberculosis trt_tuberculosis status_tuberculosis trt_tuberculosis_op tuberculosis_age_diag history_hypertension trt_hypertension status_hypertension hypertension_age_diag history_hyperlipidemia trt_hyperlipidemia status_hyperlipidemia hyperlipidemia_age_diag history_stroke trt_stroke status_stroke trt_stroke_op stroke_age_diag history_diabetes trt_diabetes status_diabetes diabetes_age_diag history_ga_duodenal_ulcer trt_ga_duodenal_ulcer status_ga_duodenal_ulcer trt_ga_duodenal_ulcer_op ga_duodenal_ulcer_age_diag history_colon_polyp trt_colon_polyp status_colon_polyp trt_colon_polyp_op colon_polyp_age_diag history_fatty_liver trt_fatty_liver status_fatty_liver fatty_liver_age_diag history_thyroid_nodules trt_thyroid_nodules status_thyroid_nodules trt_thyroid_nodules_op thyroid_nodules_age_diag history_bbt trt_bbt status_bbt trt_bbt_op bbt_age_diag trt_bbt_biopsy history_disc trt_disc status_disc trt_disc_op disc_age_diag history_gastritis trt_gastritis gastritis_age_diag history_enteritis trt_enteritis enteritis_age_diag history_hemorrhoid trt_hemorrhoid hemorrhoid_age_diag history_acute_hep trt_acute_hep acute_hep_age_diag history_hep_cirrhosis trt_hep_cirrhosis hep_cirrhosis_age_diag history_gallbladder_dis trt_gallbladder_dis gallbladder_dis_age_diag history_myoma_uteri trt_myoma_uteri_op myoma_uteri_age_diag history_cervicitis trt_cervicitis_op cervicitis_age_diag history_trauma trt_trauma trauma_age_diag history_hbv trt_hbv status_hbv hbv_age_diag history_hcv trt_hcv status_hcv hcv_age_diag history_cirrhosis trt_cirrhosis status_cirrhosis cirrhosis_age_diag history_helico_pylori trt_helico_pylori status_helico_pylori helico_pylori_age_diag history_copd trt_history_copd status_history_copd copd_age_diag history_arthritis trt_arthritis status_arthritis trt_arthritis_op arthritis_age_diag history_cataract trt_cataract status_cataract trt_cataract_op cataract_age_diag history_glaucoma trt_glaucoma status_glaucoma trt_glaucoma_op glaucoma_age_diag history_asthma_allergy trt_asthma_allergy asthma_allergy_age_diag history_asthma trt_asthma status_asthma asthma_age_diag history_coronary_dis trt_coronary_dis coronary_dis_age_diag history_angina trt_angina status_angina trt_angina_op angina_age_diag history_mi trt_mi status_mi trt_mi_op mi_age_diag history_kidney_urinary_dis trt_kidney_urinary_dis status_kidney_urinary_dis trt_kidney_urinary_dis_op kidney_urinary_dis_age_diag history_kidney_dis trt_kidney_dis kidney_dis_age_diag history_urinary_tract_dis trt_urinary_tract_dis urinary_tract_dis_age_diag history_thyroid_dis1 trt_thyroid_dis1 thyroid_dis1_age_diag history_bph trt_bph status_bph trt_bph_op bph_age_diag history_thyroid_dis2 trt_thyroid_dis2 status_thyroid_dis2 trt_thyroid_dis2_op thyroid_dis2_age_diag history_other trt_other status_other trt_other_op other_age_diag history_cancer history_cancer_stomach cancer_stomach_age_diag trt_cancer_stomach trt_cancer_stomach_op trt_cancer_stomach_ch trt_cancer_stomach_ra trt_cancer_stomach_ot history_cancer_lung cancer_lung_age_diag trt_cancer_lung trt_cancer_lung_op trt_cancer_lung_ch trt_cancer_lung_ra trt_cancer_lung_ot history_cancer_liver cancer_liver_age_diag trt_cancer_liver trt_cancer_liver_op trt_cancer_liver_ch trt_cancer_liver_ra trt_cancer_liver_ot history_cancer_colorectal cancer_colorectal_age_diag trt_cancer_colorectal trt_cancer_colorectal_op trt_cancer_colorectal_ch trt_cancer_colorectal_ra trt_cancer_colorectal_ot history_cancer_breast cancer_breast_age_diag trt_cancer_breast trt_cancer_breast_op trt_cancer_breast_ch trt_cancer_breast_ra trt_cancer_breast_ot history_cancer_cervix cancer_cervix_age_diag trt_cancer_cervix trt_cancer_cervix_op trt_cancer_cervix_ch trt_cancer_cervix_ra trt_cancer_cervix_ot history_cancer_thyroid cancer_thyroid_age_diag trt_cancer_thyroid trt_cancer_thyroid_op trt_cancer_thyroid_ch trt_cancer_thyroid_ra trt_cancer_thyroid_ot history_cancer_bladder cancer_bladder_age_diag trt_cancer_bladder trt_cancer_bladder_op trt_cancer_bladder_ch trt_cancer_bladder_ra trt_cancer_bladder_ot history_cancer_esophagus cancer_esophagus_age_diag trt_cancer_esophagus trt_cancer_esophagus_op trt_cancer_esophagus_ch trt_cancer_esophagus_ra trt_cancer_esophagus_ot history_cancer_gb_biliary cancer_gb_biliary_age_diag trt_cancer_gb_biliary trt_cancer_gb_biliary_op trt_cancer_gb_biliary_ch trt_cancer_gb_biliary_ra trt_cancer_gb_biliary_ot history_cancer_ovary cancer_ovary_age_diag trt_cancer_ovary trt_cancer_ovary_op trt_cancer_ovary_ch trt_cancer_ovary_ra trt_cancer_ovary_ot history_cancer_prostate cancer_prostate_age_diag trt_cancer_prostate trt_cancer_prostate_op trt_cancer_prostate_ch trt_cancer_prostate_ra trt_cancer_prostate_ot history_cancer_pancreas cancer_pancreas_age_diag trt_cancer_pancreas trt_cancer_pancreas_op trt_cancer_pancreas_ch trt_cancer_pancreas_ra trt_cancer_pancreas_ot history_cancer_other cancer_other_age_diag trt_cancer_other trt_cancer_other_op trt_cancer_other_ch trt_cancer_other_ra trt_cancer_other_ot med med_hypertension trt_med_hypertension med_hypertension_duration med_diabetes trt_med_diabetes med_diabetes_duration med_aspirin trt_med_aspirin med_aspirin_duration med_nsaids trt_med_nsaids med_nsaids_duration med_calcium trt_med_calcium med_calcium_duration med_iron trt_med_iron med_iron_duration med_cam trt_med_cam med_cam_duration med_beta_carotene med_beta_carotene_duration med_multi_vitamin med_multi_vitamin_duration med_vitamin_a med_vitamin_a_duration med_vitamin_b med_vitamin_b_duration med_vitamin_c med_vitamin_c_duration med_vitamin_e med_vitamin_e_duration med_other_supplements med_other_supplements_duration med_hyperlipidemia trt_med_hyperlipidemia med_warfarin trt_med_warfarin med_anticoagulant trt_med_anticoagulant med_arrhythmia trt_med_arrhythmia med_gi_digestives trt_med_gi_digestives med_liver trt_med_liver med_constipation trt_med_constipation med_thyroid_dis trt_med_thyroid_dis med_osteoporosis trt_med_osteoporosis med_female_hormones trt_med_female_hormones med_bph trt_med_bph med_respiratory_dis trt_med_respiratory_dis med_nutri_supplements trt_med_nutri_supplements med_sleeping_pills med_sleeping_pills_duration med_psychiatric trt_med_psychiatric med_other trt_med_other med_other_duration family family_hypertension_f family_hypertension_m family_hypertension_sib family_hypertension_ch family_hypertension_ff family_hypertension_fm family_hypertension_mf family_hypertension_mm family_stroke_f family_stroke_m family_stroke_sib family_stroke_ch family_stroke_ff family_stroke_fm family_stroke_mf family_stroke_mm family_diabetes_f family_diabetes_m family_diabetes_sib family_diabetes_ch family_diabetes_ff family_diabetes_fm family_diabetes_mf family_diabetes_mm family_hep_cirrhosis_f family_hep_cirrhosis_m family_hep_cirrhosis_sib family_hep_cirrhosis_ch family_hep_cirrhosis_ff family_hep_cirrhosis_fm family_hep_cirrhosis_mf family_hep_cirrhosis_mm family_dementia_f family_dementia_m family_dementia_sib family_dementia_ch family_dementia_ff family_dementia_fm family_dementia_mf family_dementia_mm family_tuberculosis_f family_tuberculosis_m family_tuberculosis_sib family_tuberculosis_ch family_tuberculosis_ff family_tuberculosis_fm family_tuberculosis_mf family_tuberculosis_mm family_mi_f family_mi_m family_mi_sib family_mi_ch family_mi_ff family_mi_fm family_mi_mf family_mi_mm family_angina_f family_angina_m family_angina_sib family_angina_ch family_angina_ff family_angina_fm family_angina_mf family_angina_mm family_other_congenital_mal_f family_other_congenital_mal_m family_other_congenital_mal_sib family_other_congenital_mal_ch family_other_congenital_mal_ff family_other_congenital_mal_fm family_other_congenital_mal_mf family_other_congenital_mal_mm family_congenital_heart_dis_f family_congenital_heart_dis_m family_congenital_heart_dis_sib family_congenital_heart_dis_ch family_congenital_heart_dis_ff family_congenital_heart_dis_fm family_congenital_heart_dis_mf family_congenital_heart_dis_mm family_cleft_lip_palate_f family_cleft_lip_palate_m family_cleft_lip_palate_sib family_cleft_lip_palate_ch family_cleft_lip_palate_ff family_cleft_lip_palate_fm family_cleft_lip_palate_mf family_cleft_lip_palate_mm family_coronary_dis_f family_coronary_dis_m family_coronary_dis_sib family_coronary_dis_ch family_coronary_dis_ff family_coronary_dis_fm family_coronary_dis_mf family_coronary_dis_mm family_asthma_copd_f family_asthma_copd_m family_asthma_copd_sib family_asthma_copd_ch family_asthma_copd_ff family_asthma_copd_fm family_asthma_copd_mf family_asthma_copd_mm family_cancer_stomach_f family_cancer_stomach_m family_cancer_stomach_sib family_cancer_stomach_ch family_cancer_stomach_ff family_cancer_stomach_fm family_cancer_stomach_mf family_cancer_stomach_mm family_cancer_breast_f family_cancer_breast_m family_cancer_breast_sib family_cancer_breast_ch family_cancer_breast_ff family_cancer_breast_fm family_cancer_breast_mf family_cancer_breast_mm family_cancer_colorectal_f family_cancer_colorectal_m family_cancer_colorectal_sib family_cancer_colorectal_ch family_cancer_colorectal_ff family_cancer_colorectal_fm family_cancer_colorectal_mf family_cancer_colorectal_mm family_cancer_lung_f family_cancer_lung_m family_cancer_lung_sib family_cancer_lung_ch family_cancer_lung_ff family_cancer_lung_fm family_cancer_lung_mf family_cancer_lung_mm family_cancer_uterine_f family_cancer_uterine_m family_cancer_uterine_sib family_cancer_uterine_ch family_cancer_uterine_ff family_cancer_uterine_fm family_cancer_uterine_mf family_cancer_uterine_mm family_cancer_liver_f family_cancer_liver_m family_cancer_liver_sib family_cancer_liver_ch family_cancer_liver_ff family_cancer_liver_fm family_cancer_liver_mf family_cancer_liver_mm family_cancer_thyroid_f family_cancer_thyroid_m family_cancer_thyroid_sib family_cancer_thyroid_ch family_cancer_thyroid_ff family_cancer_thyroid_fm family_cancer_thyroid_mf family_cancer_thyroid_mm family_cancer_ovary_f family_cancer_ovary_m family_cancer_ovary_sib family_cancer_ovary_ch family_cancer_ovary_ff family_cancer_ovary_fm family_cancer_ovary_mf family_cancer_ovary_mm family_cancer_cervix_f family_cancer_cervix_m family_cancer_cervix_sib family_cancer_cervix_ch family_cancer_cervix_ff family_cancer_cervix_fm family_cancer_cervix_mf family_cancer_cervix_mm family_cancer_gb_biliary_f family_cancer_gb_biliary_m family_cancer_gb_biliary_sib family_cancer_gb_biliary_ch family_cancer_gb_biliary_ff family_cancer_gb_biliary_fm family_cancer_gb_biliary_mf family_cancer_gb_biliary_mm family_cancer_bladder_f family_cancer_bladder_m family_cancer_bladder_sib family_cancer_bladder_ch family_cancer_bladder_ff family_cancer_bladder_fm family_cancer_bladder_mf family_cancer_bladder_mm family_cancer_esophagus_f family_cancer_esophagus_m family_cancer_esophagus_sib family_cancer_esophagus_ch family_cancer_esophagus_ff family_cancer_esophagus_fm family_cancer_esophagus_mf family_cancer_esophagus_mm family_cancer_prostate_f family_cancer_prostate_m family_cancer_prostate_sib family_cancer_prostate_ch family_cancer_prostate_ff family_cancer_prostate_fm family_cancer_prostate_mf family_cancer_prostate_mm family_cancer_pancreas_f family_cancer_pancreas_m family_cancer_pancreas_sib family_cancer_pancreas_ch family_cancer_pancreas_ff family_cancer_pancreas_fm family_cancer_pancreas_mf family_cancer_pancreas_mm family_cancer_other_f family_cancer_other_m family_cancer_other_sib family_cancer_other_ch family_cancer_other_ff family_cancer_other_fm family_cancer_other_mf family_cancer_other_mm ml1_1 ml2_1 ml3_1 ml4_1 ml5_1 ml6_1 ml7_1 ml8_1 ml_score menstruation_last_yy menstruation_last_mm menstruation_last_dd menarche_age no_menstruation menstruation_avg_duration abnormal_bleeding vaginal_discharge postmenopausal menopause_age_cat menopause_age menopause_cause female_hormones trt_female_hormones female_hormones_age female_hormones_amount female_hormones_duration pregnancy pregnancy_first_age delivery delivery_n delivery_boy delivery_girl natural_childbirth caesarean_section delivery_first_age delivery_last_age premature_birth premature_birth_n miscarriage miscarriage_natural_n miscarriage_artificial_n pap pap_first_age pap_last_age pap_freq stress_q1 stress_q2 stress_q3 stress_q4 stress_q5 stress_q6 stress_q7 stress_q8 stress_q9 stress_q10 stress_q11 stress_q12 stress_q13 stress_q14 stress_q15 stress_q16 stress_q17 stress_q18 stress_q19 stress_q20 stress_q21 stress_score sy1_1 sy1_2 sy1_3 sy1_4 sy1_5 sy1_6 sy1_7 sy1_8 sy1_9 sy1_10 sy1_11 sy1_12 sy1_13 sy1_14 sy1_15 sy1_16 sy1_17 sy1_18 sy1_19 sy1_20 sy1_21 sy2_1 sy2_2 sy2_3 sy2_4 sy2_5 sy2_6 sy2_7 sy3_1 sy3_2 sy3_3 sy3_4 sy3_5 sy3_6 sy3_7 sy3_8 sy3_9 sy3_10 sy4_1 sy4_2 sy4_3 sy4_4 sy4_5 sy4_6 sy5_1 sy5_2 sy5_3 sy5_4 sy5_5 sy5_6 sy5_7 sy6_1 sy6_2 sy6_3 sy6_4 sy6_5 sy6_6 sy6_7 sy6_8 sy6_9 sy7_1 sy7_2 sy7_3 sy7_4 sy7_5 sy7_6 sy7_7 sy8_1 sy8_2 sy8_3 sy8_4 sy8_5 sy8_6 sy8_7 sy8_8 sy8_9 sy8_10 sy9_1 sy9_2 sy9_3 sy9_4 sy9_5 sy9_6 sy9_7 sy9_8 sy9_9 sy9_10 sy9_11 sy9_12 sy9_13 sy9_14 sy9_15"

local i = 1
foreach var in `vars' {

	***** 빈도수 저장
	tab `var' dataset, matcell(freq)

	***** diff_column 저장
	mat A = (1\-1)
	mat diff_col = freq*A
	
	/*
	
	차이를 구할 때에는 뺄쌤을 해야 하므로
	행렬 계산 규칙에 의해서 계산을 엮어야 하는 
	앞의 값은 양수 뒤의 값은 음수로 계산되는 임의의 matrix가 필요함.
	mat A = (1\-1)
	
	*/

	***** diff_row 저장
	tab `var' dataset, matcell(freq)
	mat R = J(1,rowsof(freq),1)
	mat diff_row = R*freq

	/*
	***** 전체 total 저장
	matrix temp = J(2,1,1)
	matrix total = total_row*temp
	*/

	***** 코드값 저장
	levelsof `var', local(code)

	***** 저장한 값들 put excel
	putexcel A`i' = ("`var'") B`i' = ("CCE") C`i' = ("DB") D`i' = ("difference"), hcenter border(bottom) fpattern(solid, "213 213 213") //맨 윗줄
	putexcel B`i' D`i', border(left) fpattern(solid, "213 213 213")
	local i = `i' +1

	putexcel B`i' = matrix(freq) D`i' = matrix(diff_col) // 빈도수

	foreach c of local code {  //코드값
		putexcel A`i' = ("`c'") C`i', border(right)
		local i = `i' + 1
	}

	putexcel A`i' = ("Total") B`i' = matrix(total_row), border(top) //맨 아랫줄
	putexcel B`i' D`i', border(left)

	local i = `i' + 3  //두줄 띄우고 새로운 테이블 붙이기

}

// 작업 샘플 - 위에 형식으로 해 보니, 각각 dataset을 분류해서 작업하는 것은  변수의 row 변화를 카운트할 수가 없음.
// 완성!! Tab 결과 두개의 합과 차이를 표시하는 do file, 다만 total은 diff는 제외.
clear
set more off
use "Merge_201407_N.dta"

putexcel set ".\TT2.xlsx", sheet("TT") modify

***** 귀찮으니까 그냥 781개 다 돌리고 쉽시다 ^^! 오래걸려요
local vars "exam_motive exam exam_first_age exam_most_recent_yy exam_most_recent_mm exam_freq_yr exam_place marital_status education income smk_ys smk smk_duration smk_current_amount smk_start_age smk_endyr smk_packyrs alc_ys alc alc_freq alc_amount_drinks alc_start_age alc_duration alc_endyr alc_amount_grams phy overall_physical_activity phy_freq_2009 phy_duration_2009 phy_freq phy_duration phy_startyr phy_walking phy_jogging phy_tennis phy_golf phy_swimming phy_climbing phy_aerobic phy_fitness phy_other allergy allergy_penicillin allergy_sulfa allergy_contrast_agent allergy_local_anesthetic allergy_aspirin allergy_other allergy_unknown adverse_med adverse_med_antibiotics adverse_med_contrast_agent adverse_med_local_anesthetic adverse_med_aspirin_painkiller adverse_med_other surgery_stomach surgery_gallbladder surgery_colon surgery_appendix surgery_thyroid surgery_uterus surgery_ovary surgery_breast surgery_kidney surgery_other history_comorbidity history_tuberculosis trt_tuberculosis status_tuberculosis trt_tuberculosis_op tuberculosis_age_diag history_hypertension trt_hypertension status_hypertension hypertension_age_diag history_hyperlipidemia trt_hyperlipidemia status_hyperlipidemia hyperlipidemia_age_diag history_stroke trt_stroke status_stroke trt_stroke_op stroke_age_diag history_diabetes trt_diabetes status_diabetes diabetes_age_diag history_ga_duodenal_ulcer trt_ga_duodenal_ulcer status_ga_duodenal_ulcer trt_ga_duodenal_ulcer_op ga_duodenal_ulcer_age_diag history_colon_polyp trt_colon_polyp status_colon_polyp trt_colon_polyp_op colon_polyp_age_diag history_fatty_liver trt_fatty_liver status_fatty_liver fatty_liver_age_diag history_thyroid_nodules trt_thyroid_nodules status_thyroid_nodules trt_thyroid_nodules_op thyroid_nodules_age_diag history_bbt trt_bbt status_bbt trt_bbt_op bbt_age_diag trt_bbt_biopsy history_disc trt_disc status_disc trt_disc_op disc_age_diag history_gastritis trt_gastritis gastritis_age_diag history_enteritis trt_enteritis enteritis_age_diag history_hemorrhoid trt_hemorrhoid hemorrhoid_age_diag history_acute_hep trt_acute_hep acute_hep_age_diag history_hep_cirrhosis trt_hep_cirrhosis hep_cirrhosis_age_diag history_gallbladder_dis trt_gallbladder_dis gallbladder_dis_age_diag history_myoma_uteri trt_myoma_uteri_op myoma_uteri_age_diag history_cervicitis trt_cervicitis_op cervicitis_age_diag history_trauma trt_trauma trauma_age_diag history_hbv trt_hbv status_hbv hbv_age_diag history_hcv trt_hcv status_hcv hcv_age_diag history_cirrhosis trt_cirrhosis status_cirrhosis cirrhosis_age_diag history_helico_pylori trt_helico_pylori status_helico_pylori helico_pylori_age_diag history_copd trt_history_copd status_history_copd copd_age_diag history_arthritis trt_arthritis status_arthritis trt_arthritis_op arthritis_age_diag history_cataract trt_cataract status_cataract trt_cataract_op cataract_age_diag history_glaucoma trt_glaucoma status_glaucoma trt_glaucoma_op glaucoma_age_diag history_asthma_allergy trt_asthma_allergy asthma_allergy_age_diag history_asthma trt_asthma status_asthma asthma_age_diag history_coronary_dis trt_coronary_dis coronary_dis_age_diag history_angina trt_angina status_angina trt_angina_op angina_age_diag history_mi trt_mi status_mi trt_mi_op mi_age_diag history_kidney_urinary_dis trt_kidney_urinary_dis status_kidney_urinary_dis trt_kidney_urinary_dis_op kidney_urinary_dis_age_diag history_kidney_dis trt_kidney_dis kidney_dis_age_diag history_urinary_tract_dis trt_urinary_tract_dis urinary_tract_dis_age_diag history_thyroid_dis1 trt_thyroid_dis1 thyroid_dis1_age_diag history_bph trt_bph status_bph trt_bph_op bph_age_diag history_thyroid_dis2 trt_thyroid_dis2 status_thyroid_dis2 trt_thyroid_dis2_op thyroid_dis2_age_diag history_other trt_other status_other trt_other_op other_age_diag history_cancer history_cancer_stomach cancer_stomach_age_diag trt_cancer_stomach trt_cancer_stomach_op trt_cancer_stomach_ch trt_cancer_stomach_ra trt_cancer_stomach_ot history_cancer_lung cancer_lung_age_diag trt_cancer_lung trt_cancer_lung_op trt_cancer_lung_ch trt_cancer_lung_ra trt_cancer_lung_ot history_cancer_liver cancer_liver_age_diag trt_cancer_liver trt_cancer_liver_op trt_cancer_liver_ch trt_cancer_liver_ra trt_cancer_liver_ot history_cancer_colorectal cancer_colorectal_age_diag trt_cancer_colorectal trt_cancer_colorectal_op trt_cancer_colorectal_ch trt_cancer_colorectal_ra trt_cancer_colorectal_ot history_cancer_breast cancer_breast_age_diag trt_cancer_breast trt_cancer_breast_op trt_cancer_breast_ch trt_cancer_breast_ra trt_cancer_breast_ot history_cancer_cervix cancer_cervix_age_diag trt_cancer_cervix trt_cancer_cervix_op trt_cancer_cervix_ch trt_cancer_cervix_ra trt_cancer_cervix_ot history_cancer_thyroid cancer_thyroid_age_diag trt_cancer_thyroid trt_cancer_thyroid_op trt_cancer_thyroid_ch trt_cancer_thyroid_ra trt_cancer_thyroid_ot history_cancer_bladder cancer_bladder_age_diag trt_cancer_bladder trt_cancer_bladder_op trt_cancer_bladder_ch trt_cancer_bladder_ra trt_cancer_bladder_ot history_cancer_esophagus cancer_esophagus_age_diag trt_cancer_esophagus trt_cancer_esophagus_op trt_cancer_esophagus_ch trt_cancer_esophagus_ra trt_cancer_esophagus_ot history_cancer_gb_biliary cancer_gb_biliary_age_diag trt_cancer_gb_biliary trt_cancer_gb_biliary_op trt_cancer_gb_biliary_ch trt_cancer_gb_biliary_ra trt_cancer_gb_biliary_ot history_cancer_ovary cancer_ovary_age_diag trt_cancer_ovary trt_cancer_ovary_op trt_cancer_ovary_ch trt_cancer_ovary_ra trt_cancer_ovary_ot history_cancer_prostate cancer_prostate_age_diag trt_cancer_prostate trt_cancer_prostate_op trt_cancer_prostate_ch trt_cancer_prostate_ra trt_cancer_prostate_ot history_cancer_pancreas cancer_pancreas_age_diag trt_cancer_pancreas trt_cancer_pancreas_op trt_cancer_pancreas_ch trt_cancer_pancreas_ra trt_cancer_pancreas_ot history_cancer_other cancer_other_age_diag trt_cancer_other trt_cancer_other_op trt_cancer_other_ch trt_cancer_other_ra trt_cancer_other_ot med med_hypertension trt_med_hypertension med_hypertension_duration med_diabetes trt_med_diabetes med_diabetes_duration med_aspirin trt_med_aspirin med_aspirin_duration med_nsaids trt_med_nsaids med_nsaids_duration med_calcium trt_med_calcium med_calcium_duration med_iron trt_med_iron med_iron_duration med_cam trt_med_cam med_cam_duration med_beta_carotene med_beta_carotene_duration med_multi_vitamin med_multi_vitamin_duration med_vitamin_a med_vitamin_a_duration med_vitamin_b med_vitamin_b_duration med_vitamin_c med_vitamin_c_duration med_vitamin_e med_vitamin_e_duration med_other_supplements med_other_supplements_duration med_hyperlipidemia trt_med_hyperlipidemia med_warfarin trt_med_warfarin med_anticoagulant trt_med_anticoagulant med_arrhythmia trt_med_arrhythmia med_gi_digestives trt_med_gi_digestives med_liver trt_med_liver med_constipation trt_med_constipation med_thyroid_dis trt_med_thyroid_dis med_osteoporosis trt_med_osteoporosis med_female_hormones trt_med_female_hormones med_bph trt_med_bph med_respiratory_dis trt_med_respiratory_dis med_nutri_supplements trt_med_nutri_supplements med_sleeping_pills med_sleeping_pills_duration med_psychiatric trt_med_psychiatric med_other trt_med_other med_other_duration family family_hypertension_f family_hypertension_m family_hypertension_sib family_hypertension_ch family_hypertension_ff family_hypertension_fm family_hypertension_mf family_hypertension_mm family_stroke_f family_stroke_m family_stroke_sib family_stroke_ch family_stroke_ff family_stroke_fm family_stroke_mf family_stroke_mm family_diabetes_f family_diabetes_m family_diabetes_sib family_diabetes_ch family_diabetes_ff family_diabetes_fm family_diabetes_mf family_diabetes_mm family_hep_cirrhosis_f family_hep_cirrhosis_m family_hep_cirrhosis_sib family_hep_cirrhosis_ch family_hep_cirrhosis_ff family_hep_cirrhosis_fm family_hep_cirrhosis_mf family_hep_cirrhosis_mm family_dementia_f family_dementia_m family_dementia_sib family_dementia_ch family_dementia_ff family_dementia_fm family_dementia_mf family_dementia_mm family_tuberculosis_f family_tuberculosis_m family_tuberculosis_sib family_tuberculosis_ch family_tuberculosis_ff family_tuberculosis_fm family_tuberculosis_mf family_tuberculosis_mm family_mi_f family_mi_m family_mi_sib family_mi_ch family_mi_ff family_mi_fm family_mi_mf family_mi_mm family_angina_f family_angina_m family_angina_sib family_angina_ch family_angina_ff family_angina_fm family_angina_mf family_angina_mm family_other_congenital_mal_f family_other_congenital_mal_m family_other_congenital_mal_sib family_other_congenital_mal_ch family_other_congenital_mal_ff family_other_congenital_mal_fm family_other_congenital_mal_mf family_other_congenital_mal_mm family_congenital_heart_dis_f family_congenital_heart_dis_m family_congenital_heart_dis_sib family_congenital_heart_dis_ch family_congenital_heart_dis_ff family_congenital_heart_dis_fm family_congenital_heart_dis_mf family_congenital_heart_dis_mm family_cleft_lip_palate_f family_cleft_lip_palate_m family_cleft_lip_palate_sib family_cleft_lip_palate_ch family_cleft_lip_palate_ff family_cleft_lip_palate_fm family_cleft_lip_palate_mf family_cleft_lip_palate_mm family_coronary_dis_f family_coronary_dis_m family_coronary_dis_sib family_coronary_dis_ch family_coronary_dis_ff family_coronary_dis_fm family_coronary_dis_mf family_coronary_dis_mm family_asthma_copd_f family_asthma_copd_m family_asthma_copd_sib family_asthma_copd_ch family_asthma_copd_ff family_asthma_copd_fm family_asthma_copd_mf family_asthma_copd_mm family_cancer_stomach_f family_cancer_stomach_m family_cancer_stomach_sib family_cancer_stomach_ch family_cancer_stomach_ff family_cancer_stomach_fm family_cancer_stomach_mf family_cancer_stomach_mm family_cancer_breast_f family_cancer_breast_m family_cancer_breast_sib family_cancer_breast_ch family_cancer_breast_ff family_cancer_breast_fm family_cancer_breast_mf family_cancer_breast_mm family_cancer_colorectal_f family_cancer_colorectal_m family_cancer_colorectal_sib family_cancer_colorectal_ch family_cancer_colorectal_ff family_cancer_colorectal_fm family_cancer_colorectal_mf family_cancer_colorectal_mm family_cancer_lung_f family_cancer_lung_m family_cancer_lung_sib family_cancer_lung_ch family_cancer_lung_ff family_cancer_lung_fm family_cancer_lung_mf family_cancer_lung_mm family_cancer_uterine_f family_cancer_uterine_m family_cancer_uterine_sib family_cancer_uterine_ch family_cancer_uterine_ff family_cancer_uterine_fm family_cancer_uterine_mf family_cancer_uterine_mm family_cancer_liver_f family_cancer_liver_m family_cancer_liver_sib family_cancer_liver_ch family_cancer_liver_ff family_cancer_liver_fm family_cancer_liver_mf family_cancer_liver_mm family_cancer_thyroid_f family_cancer_thyroid_m family_cancer_thyroid_sib family_cancer_thyroid_ch family_cancer_thyroid_ff family_cancer_thyroid_fm family_cancer_thyroid_mf family_cancer_thyroid_mm family_cancer_ovary_f family_cancer_ovary_m family_cancer_ovary_sib family_cancer_ovary_ch family_cancer_ovary_ff family_cancer_ovary_fm family_cancer_ovary_mf family_cancer_ovary_mm family_cancer_cervix_f family_cancer_cervix_m family_cancer_cervix_sib family_cancer_cervix_ch family_cancer_cervix_ff family_cancer_cervix_fm family_cancer_cervix_mf family_cancer_cervix_mm family_cancer_gb_biliary_f family_cancer_gb_biliary_m family_cancer_gb_biliary_sib family_cancer_gb_biliary_ch family_cancer_gb_biliary_ff family_cancer_gb_biliary_fm family_cancer_gb_biliary_mf family_cancer_gb_biliary_mm family_cancer_bladder_f family_cancer_bladder_m family_cancer_bladder_sib family_cancer_bladder_ch family_cancer_bladder_ff family_cancer_bladder_fm family_cancer_bladder_mf family_cancer_bladder_mm family_cancer_esophagus_f family_cancer_esophagus_m family_cancer_esophagus_sib family_cancer_esophagus_ch family_cancer_esophagus_ff family_cancer_esophagus_fm family_cancer_esophagus_mf family_cancer_esophagus_mm family_cancer_prostate_f family_cancer_prostate_m family_cancer_prostate_sib family_cancer_prostate_ch family_cancer_prostate_ff family_cancer_prostate_fm family_cancer_prostate_mf family_cancer_prostate_mm family_cancer_pancreas_f family_cancer_pancreas_m family_cancer_pancreas_sib family_cancer_pancreas_ch family_cancer_pancreas_ff family_cancer_pancreas_fm family_cancer_pancreas_mf family_cancer_pancreas_mm family_cancer_other_f family_cancer_other_m family_cancer_other_sib family_cancer_other_ch family_cancer_other_ff family_cancer_other_fm family_cancer_other_mf family_cancer_other_mm ml1_1 ml2_1 ml3_1 ml4_1 ml5_1 ml6_1 ml7_1 ml8_1 ml_score menstruation_last_yy menstruation_last_mm menstruation_last_dd menarche_age no_menstruation menstruation_avg_duration abnormal_bleeding vaginal_discharge postmenopausal menopause_age_cat menopause_age menopause_cause female_hormones trt_female_hormones female_hormones_age female_hormones_amount female_hormones_duration pregnancy pregnancy_first_age delivery delivery_n delivery_boy delivery_girl natural_childbirth caesarean_section delivery_first_age delivery_last_age premature_birth premature_birth_n miscarriage miscarriage_natural_n miscarriage_artificial_n pap pap_first_age pap_last_age pap_freq stress_q1 stress_q2 stress_q3 stress_q4 stress_q5 stress_q6 stress_q7 stress_q8 stress_q9 stress_q10 stress_q11 stress_q12 stress_q13 stress_q14 stress_q15 stress_q16 stress_q17 stress_q18 stress_q19 stress_q20 stress_q21 stress_score sy1_1 sy1_2 sy1_3 sy1_4 sy1_5 sy1_6 sy1_7 sy1_8 sy1_9 sy1_10 sy1_11 sy1_12 sy1_13 sy1_14 sy1_15 sy1_16 sy1_17 sy1_18 sy1_19 sy1_20 sy1_21 sy2_1 sy2_2 sy2_3 sy2_4 sy2_5 sy2_6 sy2_7 sy3_1 sy3_2 sy3_3 sy3_4 sy3_5 sy3_6 sy3_7 sy3_8 sy3_9 sy3_10 sy4_1 sy4_2 sy4_3 sy4_4 sy4_5 sy4_6 sy5_1 sy5_2 sy5_3 sy5_4 sy5_5 sy5_6 sy5_7 sy6_1 sy6_2 sy6_3 sy6_4 sy6_5 sy6_6 sy6_7 sy6_8 sy6_9 sy7_1 sy7_2 sy7_3 sy7_4 sy7_5 sy7_6 sy7_7 sy8_1 sy8_2 sy8_3 sy8_4 sy8_5 sy8_6 sy8_7 sy8_8 sy8_9 sy8_10 sy9_1 sy9_2 sy9_3 sy9_4 sy9_5 sy9_6 sy9_7 sy9_8 sy9_9 sy9_10 sy9_11 sy9_12 sy9_13 sy9_14 sy9_15"

local i = 1
foreach var in `vars' {

	***** 빈도수 저장
	tab `var' dataset, matcell(freq)

	***** diff_column 저장
	mat A = (1\-1)
	mat diff_col = freq*A
	
	/*
	
	차이를 구할 때에는 뺄쌤을 해야 하므로
	행렬 계산 규칙에 의해서 계산을 엮어야 하는 
	앞의 값은 양수 뒤의 값은 음수로 계산되는 임의의 matrix가 필요함.
	mat A = (1\-1)
	
	*/

	***** diff_row 저장
	tab `var' dataset, matcell(freq)
	mat R = J(1,rowsof(freq),1)
	mat diff_row = R*freq

	/*
	***** 전체 total 저장
	matrix temp = J(2,1,1)
	matrix total = total_row*temp
	*/

	***** total_column 저장
	matrix temp = J(2,1,1)
	matrix total_col = freq*temp

	***** total_row 저장
	matrix temp = J(1,rowsof(freq),1)
	matrix total_row = temp*freq

	***** 전체 total 저장
	matrix temp = J(2,1,1)
	matrix total = total_row*temp
	
	***** 코드값 저장
	levelsof `var', local(code)

	***** 저장한 값들 put excel
	putexcel A`i' = ("`var'") B`i' = ("CCE") C`i' = ("DB") D`i' = ("Total") E`i' = ("Difference"), hcenter border(bottom) fpattern(solid, "213 213 213") //맨 윗줄
	putexcel B`i' D`i', border(left) fpattern(solid, "213 213 213")
	local i = `i' +1

	putexcel B`i' = matrix(freq) D`i' = matrix(total_col) E`i' = matrix(diff_col) // 빈도수

	foreach c of local code {  //코드값
		putexcel A`i' = ("`c'") C`i', border(right)
		local i = `i' + 1
	}

	putexcel A`i' = ("Total") B`i' = matrix(total_row) D`i' = matrix(total), border(top) //맨 아랫줄
	putexcel B`i' D`i', border(left)

	local i = `i' + 3  //두줄 띄우고 새로운 테이블 붙이기

}

// 작업 샘플 - 위에 형식으로 해 보니, 각각 dataset을 분류해서 작업하는 것은  변수의 row 변화를 카운트할 수가 없음.
// 완성!! Tab 결과 두개의 합과 차이를 다 표시하는 do file
clear
set more off
use "Merge_201407_N.dta"

putexcel set ".\TT3.xlsx", sheet("TT") modify

***** 귀찮으니까 그냥 781개 다 돌리고 쉽시다 ^^! 오래걸려요
local vars "exam_motive exam exam_first_age exam_most_recent_yy exam_most_recent_mm exam_freq_yr exam_place marital_status education income smk_ys smk smk_duration smk_current_amount smk_start_age smk_endyr smk_packyrs alc_ys alc alc_freq alc_amount_drinks alc_start_age alc_duration alc_endyr alc_amount_grams phy overall_physical_activity phy_freq_2009 phy_duration_2009 phy_freq phy_duration phy_startyr phy_walking phy_jogging phy_tennis phy_golf phy_swimming phy_climbing phy_aerobic phy_fitness phy_other allergy allergy_penicillin allergy_sulfa allergy_contrast_agent allergy_local_anesthetic allergy_aspirin allergy_other allergy_unknown adverse_med adverse_med_antibiotics adverse_med_contrast_agent adverse_med_local_anesthetic adverse_med_aspirin_painkiller adverse_med_other surgery_stomach surgery_gallbladder surgery_colon surgery_appendix surgery_thyroid surgery_uterus surgery_ovary surgery_breast surgery_kidney surgery_other history_comorbidity history_tuberculosis trt_tuberculosis status_tuberculosis trt_tuberculosis_op tuberculosis_age_diag history_hypertension trt_hypertension status_hypertension hypertension_age_diag history_hyperlipidemia trt_hyperlipidemia status_hyperlipidemia hyperlipidemia_age_diag history_stroke trt_stroke status_stroke trt_stroke_op stroke_age_diag history_diabetes trt_diabetes status_diabetes diabetes_age_diag history_ga_duodenal_ulcer trt_ga_duodenal_ulcer status_ga_duodenal_ulcer trt_ga_duodenal_ulcer_op ga_duodenal_ulcer_age_diag history_colon_polyp trt_colon_polyp status_colon_polyp trt_colon_polyp_op colon_polyp_age_diag history_fatty_liver trt_fatty_liver status_fatty_liver fatty_liver_age_diag history_thyroid_nodules trt_thyroid_nodules status_thyroid_nodules trt_thyroid_nodules_op thyroid_nodules_age_diag history_bbt trt_bbt status_bbt trt_bbt_op bbt_age_diag trt_bbt_biopsy history_disc trt_disc status_disc trt_disc_op disc_age_diag history_gastritis trt_gastritis gastritis_age_diag history_enteritis trt_enteritis enteritis_age_diag history_hemorrhoid trt_hemorrhoid hemorrhoid_age_diag history_acute_hep trt_acute_hep acute_hep_age_diag history_hep_cirrhosis trt_hep_cirrhosis hep_cirrhosis_age_diag history_gallbladder_dis trt_gallbladder_dis gallbladder_dis_age_diag history_myoma_uteri trt_myoma_uteri_op myoma_uteri_age_diag history_cervicitis trt_cervicitis_op cervicitis_age_diag history_trauma trt_trauma trauma_age_diag history_hbv trt_hbv status_hbv hbv_age_diag history_hcv trt_hcv status_hcv hcv_age_diag history_cirrhosis trt_cirrhosis status_cirrhosis cirrhosis_age_diag history_helico_pylori trt_helico_pylori status_helico_pylori helico_pylori_age_diag history_copd trt_history_copd status_history_copd copd_age_diag history_arthritis trt_arthritis status_arthritis trt_arthritis_op arthritis_age_diag history_cataract trt_cataract status_cataract trt_cataract_op cataract_age_diag history_glaucoma trt_glaucoma status_glaucoma trt_glaucoma_op glaucoma_age_diag history_asthma_allergy trt_asthma_allergy asthma_allergy_age_diag history_asthma trt_asthma status_asthma asthma_age_diag history_coronary_dis trt_coronary_dis coronary_dis_age_diag history_angina trt_angina status_angina trt_angina_op angina_age_diag history_mi trt_mi status_mi trt_mi_op mi_age_diag history_kidney_urinary_dis trt_kidney_urinary_dis status_kidney_urinary_dis trt_kidney_urinary_dis_op kidney_urinary_dis_age_diag history_kidney_dis trt_kidney_dis kidney_dis_age_diag history_urinary_tract_dis trt_urinary_tract_dis urinary_tract_dis_age_diag history_thyroid_dis1 trt_thyroid_dis1 thyroid_dis1_age_diag history_bph trt_bph status_bph trt_bph_op bph_age_diag history_thyroid_dis2 trt_thyroid_dis2 status_thyroid_dis2 trt_thyroid_dis2_op thyroid_dis2_age_diag history_other trt_other status_other trt_other_op other_age_diag history_cancer history_cancer_stomach cancer_stomach_age_diag trt_cancer_stomach trt_cancer_stomach_op trt_cancer_stomach_ch trt_cancer_stomach_ra trt_cancer_stomach_ot history_cancer_lung cancer_lung_age_diag trt_cancer_lung trt_cancer_lung_op trt_cancer_lung_ch trt_cancer_lung_ra trt_cancer_lung_ot history_cancer_liver cancer_liver_age_diag trt_cancer_liver trt_cancer_liver_op trt_cancer_liver_ch trt_cancer_liver_ra trt_cancer_liver_ot history_cancer_colorectal cancer_colorectal_age_diag trt_cancer_colorectal trt_cancer_colorectal_op trt_cancer_colorectal_ch trt_cancer_colorectal_ra trt_cancer_colorectal_ot history_cancer_breast cancer_breast_age_diag trt_cancer_breast trt_cancer_breast_op trt_cancer_breast_ch trt_cancer_breast_ra trt_cancer_breast_ot history_cancer_cervix cancer_cervix_age_diag trt_cancer_cervix trt_cancer_cervix_op trt_cancer_cervix_ch trt_cancer_cervix_ra trt_cancer_cervix_ot history_cancer_thyroid cancer_thyroid_age_diag trt_cancer_thyroid trt_cancer_thyroid_op trt_cancer_thyroid_ch trt_cancer_thyroid_ra trt_cancer_thyroid_ot history_cancer_bladder cancer_bladder_age_diag trt_cancer_bladder trt_cancer_bladder_op trt_cancer_bladder_ch trt_cancer_bladder_ra trt_cancer_bladder_ot history_cancer_esophagus cancer_esophagus_age_diag trt_cancer_esophagus trt_cancer_esophagus_op trt_cancer_esophagus_ch trt_cancer_esophagus_ra trt_cancer_esophagus_ot history_cancer_gb_biliary cancer_gb_biliary_age_diag trt_cancer_gb_biliary trt_cancer_gb_biliary_op trt_cancer_gb_biliary_ch trt_cancer_gb_biliary_ra trt_cancer_gb_biliary_ot history_cancer_ovary cancer_ovary_age_diag trt_cancer_ovary trt_cancer_ovary_op trt_cancer_ovary_ch trt_cancer_ovary_ra trt_cancer_ovary_ot history_cancer_prostate cancer_prostate_age_diag trt_cancer_prostate trt_cancer_prostate_op trt_cancer_prostate_ch trt_cancer_prostate_ra trt_cancer_prostate_ot history_cancer_pancreas cancer_pancreas_age_diag trt_cancer_pancreas trt_cancer_pancreas_op trt_cancer_pancreas_ch trt_cancer_pancreas_ra trt_cancer_pancreas_ot history_cancer_other cancer_other_age_diag trt_cancer_other trt_cancer_other_op trt_cancer_other_ch trt_cancer_other_ra trt_cancer_other_ot med med_hypertension trt_med_hypertension med_hypertension_duration med_diabetes trt_med_diabetes med_diabetes_duration med_aspirin trt_med_aspirin med_aspirin_duration med_nsaids trt_med_nsaids med_nsaids_duration med_calcium trt_med_calcium med_calcium_duration med_iron trt_med_iron med_iron_duration med_cam trt_med_cam med_cam_duration med_beta_carotene med_beta_carotene_duration med_multi_vitamin med_multi_vitamin_duration med_vitamin_a med_vitamin_a_duration med_vitamin_b med_vitamin_b_duration med_vitamin_c med_vitamin_c_duration med_vitamin_e med_vitamin_e_duration med_other_supplements med_other_supplements_duration med_hyperlipidemia trt_med_hyperlipidemia med_warfarin trt_med_warfarin med_anticoagulant trt_med_anticoagulant med_arrhythmia trt_med_arrhythmia med_gi_digestives trt_med_gi_digestives med_liver trt_med_liver med_constipation trt_med_constipation med_thyroid_dis trt_med_thyroid_dis med_osteoporosis trt_med_osteoporosis med_female_hormones trt_med_female_hormones med_bph trt_med_bph med_respiratory_dis trt_med_respiratory_dis med_nutri_supplements trt_med_nutri_supplements med_sleeping_pills med_sleeping_pills_duration med_psychiatric trt_med_psychiatric med_other trt_med_other med_other_duration family family_hypertension_f family_hypertension_m family_hypertension_sib family_hypertension_ch family_hypertension_ff family_hypertension_fm family_hypertension_mf family_hypertension_mm family_stroke_f family_stroke_m family_stroke_sib family_stroke_ch family_stroke_ff family_stroke_fm family_stroke_mf family_stroke_mm family_diabetes_f family_diabetes_m family_diabetes_sib family_diabetes_ch family_diabetes_ff family_diabetes_fm family_diabetes_mf family_diabetes_mm family_hep_cirrhosis_f family_hep_cirrhosis_m family_hep_cirrhosis_sib family_hep_cirrhosis_ch family_hep_cirrhosis_ff family_hep_cirrhosis_fm family_hep_cirrhosis_mf family_hep_cirrhosis_mm family_dementia_f family_dementia_m family_dementia_sib family_dementia_ch family_dementia_ff family_dementia_fm family_dementia_mf family_dementia_mm family_tuberculosis_f family_tuberculosis_m family_tuberculosis_sib family_tuberculosis_ch family_tuberculosis_ff family_tuberculosis_fm family_tuberculosis_mf family_tuberculosis_mm family_mi_f family_mi_m family_mi_sib family_mi_ch family_mi_ff family_mi_fm family_mi_mf family_mi_mm family_angina_f family_angina_m family_angina_sib family_angina_ch family_angina_ff family_angina_fm family_angina_mf family_angina_mm family_other_congenital_mal_f family_other_congenital_mal_m family_other_congenital_mal_sib family_other_congenital_mal_ch family_other_congenital_mal_ff family_other_congenital_mal_fm family_other_congenital_mal_mf family_other_congenital_mal_mm family_congenital_heart_dis_f family_congenital_heart_dis_m family_congenital_heart_dis_sib family_congenital_heart_dis_ch family_congenital_heart_dis_ff family_congenital_heart_dis_fm family_congenital_heart_dis_mf family_congenital_heart_dis_mm family_cleft_lip_palate_f family_cleft_lip_palate_m family_cleft_lip_palate_sib family_cleft_lip_palate_ch family_cleft_lip_palate_ff family_cleft_lip_palate_fm family_cleft_lip_palate_mf family_cleft_lip_palate_mm family_coronary_dis_f family_coronary_dis_m family_coronary_dis_sib family_coronary_dis_ch family_coronary_dis_ff family_coronary_dis_fm family_coronary_dis_mf family_coronary_dis_mm family_asthma_copd_f family_asthma_copd_m family_asthma_copd_sib family_asthma_copd_ch family_asthma_copd_ff family_asthma_copd_fm family_asthma_copd_mf family_asthma_copd_mm family_cancer_stomach_f family_cancer_stomach_m family_cancer_stomach_sib family_cancer_stomach_ch family_cancer_stomach_ff family_cancer_stomach_fm family_cancer_stomach_mf family_cancer_stomach_mm family_cancer_breast_f family_cancer_breast_m family_cancer_breast_sib family_cancer_breast_ch family_cancer_breast_ff family_cancer_breast_fm family_cancer_breast_mf family_cancer_breast_mm family_cancer_colorectal_f family_cancer_colorectal_m family_cancer_colorectal_sib family_cancer_colorectal_ch family_cancer_colorectal_ff family_cancer_colorectal_fm family_cancer_colorectal_mf family_cancer_colorectal_mm family_cancer_lung_f family_cancer_lung_m family_cancer_lung_sib family_cancer_lung_ch family_cancer_lung_ff family_cancer_lung_fm family_cancer_lung_mf family_cancer_lung_mm family_cancer_uterine_f family_cancer_uterine_m family_cancer_uterine_sib family_cancer_uterine_ch family_cancer_uterine_ff family_cancer_uterine_fm family_cancer_uterine_mf family_cancer_uterine_mm family_cancer_liver_f family_cancer_liver_m family_cancer_liver_sib family_cancer_liver_ch family_cancer_liver_ff family_cancer_liver_fm family_cancer_liver_mf family_cancer_liver_mm family_cancer_thyroid_f family_cancer_thyroid_m family_cancer_thyroid_sib family_cancer_thyroid_ch family_cancer_thyroid_ff family_cancer_thyroid_fm family_cancer_thyroid_mf family_cancer_thyroid_mm family_cancer_ovary_f family_cancer_ovary_m family_cancer_ovary_sib family_cancer_ovary_ch family_cancer_ovary_ff family_cancer_ovary_fm family_cancer_ovary_mf family_cancer_ovary_mm family_cancer_cervix_f family_cancer_cervix_m family_cancer_cervix_sib family_cancer_cervix_ch family_cancer_cervix_ff family_cancer_cervix_fm family_cancer_cervix_mf family_cancer_cervix_mm family_cancer_gb_biliary_f family_cancer_gb_biliary_m family_cancer_gb_biliary_sib family_cancer_gb_biliary_ch family_cancer_gb_biliary_ff family_cancer_gb_biliary_fm family_cancer_gb_biliary_mf family_cancer_gb_biliary_mm family_cancer_bladder_f family_cancer_bladder_m family_cancer_bladder_sib family_cancer_bladder_ch family_cancer_bladder_ff family_cancer_bladder_fm family_cancer_bladder_mf family_cancer_bladder_mm family_cancer_esophagus_f family_cancer_esophagus_m family_cancer_esophagus_sib family_cancer_esophagus_ch family_cancer_esophagus_ff family_cancer_esophagus_fm family_cancer_esophagus_mf family_cancer_esophagus_mm family_cancer_prostate_f family_cancer_prostate_m family_cancer_prostate_sib family_cancer_prostate_ch family_cancer_prostate_ff family_cancer_prostate_fm family_cancer_prostate_mf family_cancer_prostate_mm family_cancer_pancreas_f family_cancer_pancreas_m family_cancer_pancreas_sib family_cancer_pancreas_ch family_cancer_pancreas_ff family_cancer_pancreas_fm family_cancer_pancreas_mf family_cancer_pancreas_mm family_cancer_other_f family_cancer_other_m family_cancer_other_sib family_cancer_other_ch family_cancer_other_ff family_cancer_other_fm family_cancer_other_mf family_cancer_other_mm ml1_1 ml2_1 ml3_1 ml4_1 ml5_1 ml6_1 ml7_1 ml8_1 ml_score menstruation_last_yy menstruation_last_mm menstruation_last_dd menarche_age no_menstruation menstruation_avg_duration abnormal_bleeding vaginal_discharge postmenopausal menopause_age_cat menopause_age menopause_cause female_hormones trt_female_hormones female_hormones_age female_hormones_amount female_hormones_duration pregnancy pregnancy_first_age delivery delivery_n delivery_boy delivery_girl natural_childbirth caesarean_section delivery_first_age delivery_last_age premature_birth premature_birth_n miscarriage miscarriage_natural_n miscarriage_artificial_n pap pap_first_age pap_last_age pap_freq stress_q1 stress_q2 stress_q3 stress_q4 stress_q5 stress_q6 stress_q7 stress_q8 stress_q9 stress_q10 stress_q11 stress_q12 stress_q13 stress_q14 stress_q15 stress_q16 stress_q17 stress_q18 stress_q19 stress_q20 stress_q21 stress_score sy1_1 sy1_2 sy1_3 sy1_4 sy1_5 sy1_6 sy1_7 sy1_8 sy1_9 sy1_10 sy1_11 sy1_12 sy1_13 sy1_14 sy1_15 sy1_16 sy1_17 sy1_18 sy1_19 sy1_20 sy1_21 sy2_1 sy2_2 sy2_3 sy2_4 sy2_5 sy2_6 sy2_7 sy3_1 sy3_2 sy3_3 sy3_4 sy3_5 sy3_6 sy3_7 sy3_8 sy3_9 sy3_10 sy4_1 sy4_2 sy4_3 sy4_4 sy4_5 sy4_6 sy5_1 sy5_2 sy5_3 sy5_4 sy5_5 sy5_6 sy5_7 sy6_1 sy6_2 sy6_3 sy6_4 sy6_5 sy6_6 sy6_7 sy6_8 sy6_9 sy7_1 sy7_2 sy7_3 sy7_4 sy7_5 sy7_6 sy7_7 sy8_1 sy8_2 sy8_3 sy8_4 sy8_5 sy8_6 sy8_7 sy8_8 sy8_9 sy8_10 sy9_1 sy9_2 sy9_3 sy9_4 sy9_5 sy9_6 sy9_7 sy9_8 sy9_9 sy9_10 sy9_11 sy9_12 sy9_13 sy9_14 sy9_15"

local i = 1
foreach var in `vars' {

	***** 빈도수 저장
	tab `var' dataset, matcell(freq)

	***** diff_column 저장
	mat A = (1\-1)
	mat diff_col = freq*A
	
	/*
	
	차이를 구할 때에는 뺄쌤을 해야 하므로
	행렬 계산 규칙에 의해서 
	앞의 값은 양수, 뒤의 값은 음수로 계산되는 임의의 matrix가 필요함.
	mat A = (1\-1)
	
	*/

	***** diff_row 저장
	mat R = J(1,rowsof(freq),1)
	mat diff_row = R*freq

	***** 전체 diff 저장
	matrix temp = (1\-1)
	matrix diff = diff_row*temp

	***** total_column 저장
	matrix temp = J(2,1,1)
	matrix total_col = freq*temp

	***** total_row 저장
	matrix temp = J(1,rowsof(freq),1)
	matrix total_row = temp*freq

	***** 전체 total 저장
	matrix temp = J(2,1,1)
	matrix total = total_row*temp
	
	***** 코드값 저장
	levelsof `var', local(code)

	***** 저장한 값들 put excel
	putexcel A`i' = ("`var'") B`i' = ("CCE") C`i' = ("DB") D`i' = ("Total") E`i' = ("Difference"), hcenter border(bottom) fpattern(solid, "213 213 213") //맨 윗줄
	putexcel B`i' D`i', border(left) fpattern(solid, "213 213 213")
	local i = `i' +1

	putexcel B`i' = matrix(freq) D`i' = matrix(total_col) E`i' = matrix(diff_col) // 빈도수

	foreach c of local code {  //코드값
		putexcel A`i' = ("`c'") C`i', border(right)
		local i = `i' + 1
	}

	putexcel A`i' = ("Total") B`i' = matrix(total_row) D`i' = matrix(total) E`i' = matrix(diff), border(top) //맨 아랫줄
	putexcel B`i' D`i', border(left)

	local i = `i' + 3  //두줄 띄우고 새로운 테이블 붙이기

}
